--- #YAML:1.0
name: Class-MethodMaker
version: 2.03
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Class::MethodMaker:
    file: lib/Class/MethodMaker.pm
    version: 2.00
  Class::MethodMaker::Constants:
    file: lib/Class/MethodMaker/Constants.pm
  Class::MethodMaker::Engine:
    file: lib/Class/MethodMaker/Engine.pm
    version: 2.03
  Class::MethodMaker::OptExt:
    file: lib/Class/MethodMaker/OptExt.pm
  Class::MethodMaker::V1Compat:
    file: lib/Class/MethodMaker/V1Compat.pm
generated_by: Module::Build version 0.21
